# Healthcare Provider Disclosure Policy Configuration
# This file defines the rules and thresholds for disclosure compliance

version: "1.0.0"
last_updated: "2025-08-07"

# Policy Categories
policies:
  financial_disclosures:
    description: "Policies related to financial relationships and payments"
    rules:
      - id: "FIN-001"
        name: "Annual Payment Threshold"
        description: "Total annual payments from a single entity"
        threshold: 5000
        currency: "USD"
        action: "review_required"
        
      - id: "FIN-002"
        name: "Speaking Fee Limit"
        description: "Maximum allowed speaking fee per engagement"
        threshold: 10000
        currency: "USD"
        action: "approval_required"
        
      - id: "FIN-003"
        name: "Research Grant Disclosure"
        description: "Research grants must be disclosed"
        threshold: 0
        currency: "USD"
        action: "mandatory_disclosure"

  equity_interests:
    description: "Policies for equity and ownership interests"
    rules:
      - id: "EQ-001"
        name: "Stock Ownership"
        description: "Ownership in healthcare-related companies"
        threshold: 5000
        currency: "USD"
        action: "review_required"
        
      - id: "EQ-002"
        name: "Board Membership"
        description: "Board or advisory positions"
        threshold: 0
        action: "mandatory_disclosure"

  consulting_agreements:
    description: "Policies for consulting and advisory relationships"
    rules:
      - id: "CON-001"
        name: "Consulting Fee Annual Cap"
        description: "Maximum annual consulting fees from single entity"
        threshold: 25000
        currency: "USD"
        action: "approval_required"
        
      - id: "CON-002"
        name: "Time Commitment"
        description: "Maximum days per year for consulting"
        threshold: 20
        unit: "days"
        action: "review_required"

  gifts_and_meals:
    description: "Policies for gifts, meals, and entertainment"
    rules:
      - id: "GIFT-001"
        name: "Individual Gift Value"
        description: "Maximum value for individual gifts"
        threshold: 100
        currency: "USD"
        action: "allowed"
        
      - id: "GIFT-002"
        name: "Annual Gift Total"
        description: "Maximum annual total from single source"
        threshold: 500
        currency: "USD"
        action: "review_required"

# Compliance Actions
compliance_actions:
  allowed:
    description: "Disclosure is within policy limits"
    severity: "low"
    color: "green"
    
  review_required:
    description: "Requires compliance team review"
    severity: "medium"
    color: "yellow"
    
  approval_required:
    description: "Requires institutional approval"
    severity: "high"
    color: "orange"
    
  mandatory_disclosure:
    description: "Must be disclosed regardless of amount"
    severity: "required"
    color: "blue"
    
  prohibited:
    description: "Not allowed under any circumstances"
    severity: "critical"
    color: "red"

# Risk Scoring
risk_scoring:
  weights:
    financial_amount: 0.4
    number_of_relationships: 0.2
    conflict_type: 0.2
    disclosure_timeliness: 0.1
    historical_compliance: 0.1
    
  thresholds:
    low_risk: 30
    medium_risk: 60
    high_risk: 80

# Reporting Configuration
reporting:
  frequency: "monthly"
  formats:
    - "pdf"
    - "excel"
    - "dashboard"
  
  recipients:
    compliance_team: true
    department_heads: true
    individual_providers: true