# COI Operational Thresholds Configuration
# ==========================================
# This file provides configurable risk indicators and thresholds that work alongside
# the policy configuration (coi-policies.yaml) to enable risk-based compliance review.
# 
# These thresholds are based on industry best practices, CMS Open Payments standards,
# and federal regulations, but can be adjusted by the Chief Compliance Officer
# to match organizational risk tolerance.
#
# Last Updated: 2025-08-08
# Version: 1.0.0

metadata:
  version: "1.0.0"
  last_updated: "2025-08-08"
  purpose: "Operational thresholds for COI risk assessment and management"
  companion_file: "coi-policies.yaml"
  regulatory_alignment:
    - "CMS Open Payments (42 USC 1320a-7h)"
    - "PHS Research COI (42 CFR Part 50)"
    - "FDA Clinical Trials (21 CFR Part 54)"
    - "OIG Compliance Guidance"

# Risk Assessment Tiers
# Based on financial value and requiring progressively stringent management
# These tiers implement the conflict management procedures from Policy Sections 4.7 and 4.9
risk_tiers:
  policy_reference: "coi-policies.yaml#conflict_management"  # Policy Sections 4.7, 4.9
  tier_1_low:
    label: "Low Risk"
    range_min: 1000
    range_max: 5000
    description: "Minimal risk relationships requiring basic documentation"
    policy_clause: "4.7"  # Determination of conflict by reasonable judgment
    management_requirements:
      review_level: "automated"
      approval_authority: "system_auto_approve"
      management_plan: false
      monitoring_frequency: "annual"
      documentation: "basic_disclosure_form"
    typical_scenarios:
      - "Small consulting fees"
      - "Modest honoraria"
      - "Educational materials"
      - "Meals under CMS limits"
    
  tier_2_moderate:
    label: "Moderate Risk"
    range_min: 5001
    range_max: 25000
    description: "Moderate risk requiring manager review and potential management plan"
    policy_clause: "4.9.2"  # May appoint disinterested person to investigate alternatives
    management_requirements:
      review_level: "manager"
      approval_authority: "department_manager"
      management_plan: "case_by_case"
      monitoring_frequency: "semi_annual"
      documentation: "detailed_disclosure_with_justification"
    typical_scenarios:
      - "Speaking engagements"
      - "Advisory board participation"
      - "Moderate consulting arrangements"
      - "Research funding (non-sponsored)"
    
  tier_3_high:
    label: "High Risk"
    range_min: 25001
    range_max: 100000
    description: "High risk requiring committee review and management plan"
    policy_clause: "4.9.1"  # Must abstain from discussion and voting
    management_requirements:
      review_level: "committee"
      approval_authority: "coi_committee"
      management_plan: true
      monitoring_frequency: "quarterly"
      documentation: "comprehensive_disclosure_with_mitigation"
      additional_requirements:
        - "Conflict management plan required"
        - "Regular attestations"
        - "Potential public disclosure"
    typical_scenarios:
      - "Significant equity interests"
      - "Major consulting contracts"
      - "Board positions with compensation"
      - "Sponsored research agreements"
    
  tier_4_critical:
    label: "Critical Risk"
    range_min: 100001
    range_max: null  # No upper limit
    description: "Critical risk requiring board notification and comprehensive management"
    policy_clause: "4.8"  # May constitute insurmountable conflict
    management_requirements:
      review_level: "board"
      approval_authority: "board_or_designated_committee"
      management_plan: true
      monitoring_frequency: "monthly"
      documentation: "full_board_package"
      additional_requirements:
        - "Board notification required"
        - "Comprehensive management plan"
        - "Consider recusal or divestiture"
        - "Legal review recommended"
        - "Public disclosure likely required"
    typical_scenarios:
      - "Major ownership interests"
      - "Executive positions in related entities"
      - "Significant intellectual property rights"
      - "Large sponsored research programs"

# Disclosure Triggers
# Thresholds that trigger mandatory disclosure requirements
# These implement disclosure timing requirements from Policy Sections 4.3-4.4
disclosure_triggers:
  policy_reference: "coi-policies.yaml#disclosure_timing"  # Policy Sections 4.3-4.4
  
  # Payment-based triggers (aligned with CMS Open Payments)
  payments:
    policy_clause: "5.9"  # Financial Interest definition
    individual_payment:
      threshold: 100  # Single payment threshold
      description: "Individual payments exceeding this amount must be tracked"
      regulatory_basis: "CMS Open Payments de minimis exception"
      
    annual_aggregate:
      threshold: 1000  # Annual cumulative threshold
      description: "Total annual payments triggering full disclosure"
      regulatory_basis: "Industry best practice"
      
    meals_entertainment:
      threshold: 25  # Per occurrence
      annual_limit: 500
      description: "Meals and entertainment threshold"
      regulatory_basis: "CMS guidelines and state regulations"
    
  # Travel and lodging (immediate disclosure required)
  travel:
    any_amount_disclosure: true
    threshold: 0  # Any amount must be disclosed
    description: "Travel and lodging require immediate disclosure"
    exceptions:
      - "Government agencies"
      - "Academic institutions"
      - "Professional societies (educational events)"
    
  # Research-specific thresholds
  research:
    phs_threshold: 5000  # Public Health Service threshold
    fda_threshold: 25000  # FDA significant financial interest
    industry_sponsored: 10000
    description: "Research-related financial interests"
    includes:
      - "Consulting fees from sponsors"
      - "Equity in sponsor companies"
      - "Intellectual property rights"
      - "Travel from sponsors"
    
  # Speaking and teaching
  speaking:
    per_engagement: 2500
    annual_maximum: 25000
    speaker_bureau_participation: 0  # Any amount
    description: "Speaking fees and honoraria"
    
  # Equity interests
  equity:
    policy_clause: "5.9"  # Financial Interest exclusion for <1% publicly traded
    publicly_traded:
      threshold: 5000
      percentage_ownership: 1  # 1% ownership regardless of value
      description: "Publicly traded securities"
      
    privately_held:
      threshold: 0  # Any amount
      description: "Any equity in private companies must be disclosed"
      
    stock_options:
      threshold: 0  # Any amount
      description: "Options or rights to acquire equity"

# Risk Scoring Matrix
# Weighted factors for automated risk assessment
# Implements determination procedures from Policy Section 4.7
risk_scoring:
  policy_reference: "coi-policies.yaml#conflict_management.determination"  # Policy Section 4.7
  
  # Component weights (must total 100%)
  factor_weights:
    financial_amount: 40  # Percentage weight
    decision_authority: 25
    relationship_type: 20
    service_overlap: 10
    frequency: 5
    
  # Scoring scales for each factor
  financial_amount_scale:
    minimal: 
      range: "0-1000"
      score: 5
    low:
      range: "1001-5000"
      score: 20
    moderate:
      range: "5001-25000"
      score: 40
    high:
      range: "25001-100000"
      score: 70
    critical:
      range: ">100000"
      score: 100
      
  decision_authority_scale:
    no_authority:
      description: "No decision-making role"
      score: 0
    staff_level:
      description: "Staff with limited influence"
      score: 25
    manager_level:
      description: "Department manager or director"
      score: 50
    executive_level:
      description: "C-suite or VP level"
      score: 75
    board_level:
      description: "Board member or trustee"
      score: 100
      
  relationship_type_scale:
    indirect:
      description: "Indirect relationship through family"
      score: 30
    passive:
      description: "Passive investment only"
      score: 40
    active_limited:
      description: "Active but limited engagement"
      score: 60
    active_significant:
      description: "Active and significant involvement"
      score: 100
      
  service_overlap_scale:
    none:
      description: "No overlap with entity services"
      score: 0
    minimal:
      description: "Minimal service overlap"
      score: 25
    moderate:
      description: "Some service overlap"
      score: 50
    significant:
      description: "Significant service overlap"
      score: 75
    direct_competition:
      description: "Direct competitor"
      score: 100
      
  frequency_scale:
    one_time:
      description: "Single occurrence"
      score: 20
    occasional:
      description: "Less than quarterly"
      score: 40
    regular:
      description: "Quarterly or monthly"
      score: 70
    ongoing:
      description: "Continuous relationship"
      score: 100

# Management Actions by Risk Score
# Implements management procedures from Policy Sections 4.9 and 4.11
management_by_score:
  policy_reference: "coi-policies.yaml#conflict_management.procedures_when_conflict_exists"  # Policy Section 4.9
  
  low_risk:
    score_range: "0-25"
    label: "Document Only"
    actions:
      - "Record in COI database"
      - "Annual attestation"
      - "No active management required"
    review_cycle: "annual"
    
  moderate_risk:
    score_range: "26-50"
    label: "Manager Review Required"
    actions:
      - "Manager review and approval"
      - "Document mitigation measures"
      - "Semi-annual monitoring"
      - "May require disclosure to affected parties"
    review_cycle: "semi_annual"
    
  high_risk:
    score_range: "51-75"
    label: "Committee Review Required"
    actions:
      - "COI Committee review"
      - "Formal management plan required"
      - "Quarterly monitoring"
      - "Disclosure to affected parties"
      - "May require recusal from decisions"
    review_cycle: "quarterly"
    
  critical_risk:
    score_range: "76-100"
    label: "Board Review Required"
    actions:
      - "Board or Executive Committee review"
      - "Comprehensive management plan"
      - "Monthly monitoring"
      - "Public disclosure may be required"
      - "Consider recusal or divestiture"
      - "Legal counsel consultation"
    review_cycle: "monthly"

# Automated Review Flags
# Conditions that trigger automatic escalation or review
# Implements review requirements from Policy Sections 4.6, 4.11, 4.14
automated_flags:
  policy_reference: "coi-policies.yaml#review_requirements"  # Policy Sections 4.6, 4.11, 4.14
  
  multiple_relationships:
    trigger: "More than 3 relationships with same entity"
    action: "Escalate to committee review"
    
  rapid_increase:
    trigger: "Value increase >50% year-over-year"
    action: "Flag for enhanced review"
    
  competitor_relationship:
    trigger: "Relationship with known competitor"
    action: "Immediate committee review"
    policy_clause: "4.8.3"  # Competing healthcare is insurmountable conflict
    
  government_official:
    trigger: "Involves government official"
    action: "Legal review required"
    policy_clause: "4.8.2"  # Elected officials are insurmountable conflict
    
  research_sponsor:
    trigger: "PI has financial interest in sponsor"
    action: "Research compliance review"
    
  cumulative_threshold:
    trigger: "Total interests exceed $250,000"
    action: "Board notification required"
    
  pattern_detection:
    trigger: "Unusual pattern of disclosures"
    action: "Compliance audit triggered"

# Monitoring Frequencies
# Review cycles based on risk level and compliance history
monitoring_schedule:
  
  standard_cycles:
    clean_history:
      low_risk: "annual"
      moderate_risk: "semi_annual"
      high_risk: "quarterly"
      critical_risk: "monthly"
      
    prior_issues:
      low_risk: "semi_annual"
      moderate_risk: "quarterly"
      high_risk: "monthly"
      critical_risk: "bi_weekly"
      
  escalation_triggers:
    - "Missed disclosure deadline"
    - "Undisclosed relationship discovered"
    - "Violation of management plan"
    - "Regulatory inquiry"
    - "Media attention"

# Industry-Specific Adjustments
# Different thresholds for different organization types
industry_adjustments:
  
  healthcare_provider:
    modifier: 1.0  # Base thresholds
    description: "Standard healthcare provider organization"
    regulatory_focus:
      - "CMS Open Payments"
      - "Stark Law"
      - "Anti-Kickback Statute"
      
  academic_medical_center:
    modifier: 1.2  # 20% higher thresholds
    description: "Teaching hospitals and AMCs"
    regulatory_focus:
      - "PHS research regulations"
      - "NIH requirements"
      - "CMS teaching hospital rules"
      
  research_institution:
    modifier: 0.8  # 20% lower thresholds
    description: "Pure research organizations"
    regulatory_focus:
      - "42 CFR Part 50"
      - "NSF conflicts policy"
      - "FDA clinical trial requirements"
      
  specialty_practice:
    modifier: 0.9  # 10% lower thresholds
    description: "Specialized medical practices"
    regulatory_focus:
      - "State medical board requirements"
      - "Specialty society guidelines"

# Integration Configuration
integration:
  
  # Links to policy clauses - Direct mapping to Texas Health policy sections
  policy_references:
    disclosure_requirements: "coi-policies.yaml#disclosure_timing"  # Sections 4.3-4.4
    covered_persons: "coi-policies.yaml#covered_persons"  # Section 4.2
    insurmountable_conflicts: "coi-policies.yaml#insurmountable_conflicts"  # Section 4.8
    management_procedures: "coi-policies.yaml#conflict_management"  # Sections 4.7, 4.9
    compensation_restrictions: "coi-policies.yaml#compensation_restrictions"  # Section 4.12
    violations_enforcement: "coi-policies.yaml#violations"  # Section 4.13
    review_documentation: "coi-policies.yaml#review_requirements"  # Sections 4.6, 4.11, 4.14
    financial_interests_definition: "coi-policies.yaml#interests_to_disclose.financial_interests"  # Section 5.9
    one_percent_exclusion: "coi-policies.yaml#interests_to_disclose.financial_interests.exclusion"  # 1% rule
    
  # BigQuery field mappings for Open Payments data
  bigquery_mappings:
    payment_amount: "open_payments.total_amount_usd"
    payment_date: "open_payments.payment_date"
    payer_name: "open_payments.applicable_manufacturer_name"
    recipient_id: "open_payments.physician_profile_id"
    payment_nature: "open_payments.nature_of_payment"
    
  # Dashboard visualization thresholds
  dashboard_config:
    risk_colors:
      low: "#28a745"  # Green
      moderate: "#ffc107"  # Yellow
      high: "#fd7e14"  # Orange
      critical: "#dc3545"  # Red
    chart_breakpoints:
      - 1000
      - 5000
      - 25000
      - 100000
      
  # Alert trigger points
  alert_thresholds:
    email_notification: 5000
    manager_alert: 25000
    committee_alert: 50000
    board_alert: 100000
    regulatory_filing: 250000

# Configuration Management
configuration:
  
  # Adjustment authorization
  adjustment_authority:
    thresholds: "Chief Compliance Officer"
    weights: "COI Committee"
    monitoring: "Compliance Department"
    
  # Change tracking
  change_log_required: true
  approval_required_for_changes: true
  
  # Review schedule
  annual_review_date: "January 31"
  regulatory_update_check: "quarterly"
  
  # Override capability
  emergency_override:
    authorized_by: "Chief Compliance Officer or General Counsel"
    documentation_required: true
    board_notification: true

# Reporting and Analytics
reporting:
  
  # Standard reports
  standard_reports:
    - "Monthly COI summary"
    - "Quarterly risk analysis"
    - "Annual compliance report"
    - "Board dashboard"
    
  # Key metrics
  key_metrics:
    - "Total disclosures by tier"
    - "Average risk score"
    - "Management plan compliance rate"
    - "Time to resolution"
    - "Year-over-year trends"
    
  # Benchmarking
  industry_benchmarks:
    disclosure_rate: "8-12%"  # Percentage requiring review
    high_risk_rate: "1-2%"  # Percentage requiring recusal/divestiture
    compliance_rate: "95%"  # Target compliance rate
    resolution_time: "30 days"  # Target resolution timeframe

# Notes for Implementation
implementation_notes:
  - "All dollar amounts are in USD"
  - "Thresholds are cumulative per 12-month period unless otherwise specified"
  - "Family member interests are aggregated with individual's interests"
  - "International relationships may require currency conversion"
  - "Government agency relationships have separate reporting requirements"
  - "These thresholds supplement but do not replace policy requirements"