# Provider Profile Web Scraper Configuration
# DA-173: Provider Profile Web Enrichment POC

# OpenAI Configuration
openai:
  api_key: ${OPENAI_API_KEY}  # Set via environment variable
  model: gpt-4o
  max_tokens: 3000
  temperature: 0  # Deterministic responses for consistency
  top_p: 0.8
  
# Web Search Configuration  
web_search:
  search_context_size: high  # high, medium, low
  user_location:
    type: approximate
  max_sources: 20  # Maximum number of sources to consider
  search_depth: comprehensive  # comprehensive, standard, quick
  
# Quality Settings
quality:
  min_confidence_threshold: 0.7  # Minimum confidence to include data
  require_citations: true  # All data must have source citations
  max_retry_attempts: 3  # Retries for failed requests
  retry_delay_seconds: 2  # Exponential backoff base
  validate_npi: true  # Validate NPI numbers
  cross_reference_sources: true  # Verify data across multiple sources
  
# Processing Settings
processing:
  timeout_seconds: 60  # Maximum time per provider
  batch_size: 10  # For bulk processing
  max_workers: 1  # Concurrent workers (1 for POC)
  rate_limit_per_minute: 30  # API rate limiting
  checkpoint_frequency: 5  # Save checkpoint every N providers
  
# Storage Settings
storage:
  output_dir: data/output
  log_dir: data/logs
  checkpoint_dir: data/checkpoints
  create_timestamped_folders: true
  output_format: json  # json, csv, both
  pretty_print_json: true
  
# Logging Configuration
logging:
  level: DEBUG  # DEBUG, INFO, WARNING, ERROR
  capture_full_responses: true  # Store complete API responses
  log_rotation: daily  # daily, weekly, size
  max_log_size_mb: 100
  backup_count: 30  # Number of backup logs to keep
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Source Credibility Weights
source_credibility:
  hospital_website: 1.0
  university_website: 0.95
  government_database: 1.0
  professional_directory: 0.8
  research_database: 0.9
  news_article: 0.6
  professional_society: 0.85
  company_website: 0.75
  
# Field Priority Weights (for completeness scoring)
field_priority:
  # Required fields
  name: 1.0
  specialty: 0.9
  current_positions: 0.9
  hospital_affiliations: 0.85
  
  # Important fields
  education: 0.8
  certifications: 0.8
  npi: 0.75
  practice_locations: 0.75
  
  # Nice to have fields
  research: 0.6
  publications: 0.6
  industry_relationships: 0.7
  board_memberships: 0.7
  speaking_engagements: 0.5
  awards: 0.4
  
# Manual Review Triggers
manual_review:
  confidence_threshold: 0.7  # Flag if below
  completeness_threshold: 0.6  # Flag if below
  conflicting_data: true  # Flag on conflicts
  high_value_titles:  # Flag these positions
    - "Chief"
    - "Chair"
    - "President"
    - "Director"
    - "Dean"
    
# Data Validation Rules
validation:
  npi:
    length: 10
    type: numeric
    luhn_check: true
  dates:
    format: "YYYY-MM-DD"
    allow_future: false
    min_year: 1950
  urls:
    validate: true
    timeout: 5
  text:
    max_length: 10000
    strip_html: true
    
# Excluded Domains (won't scrape from these)
excluded_domains:
  - facebook.com
  - twitter.com
  - instagram.com
  - tiktok.com
  - reddit.com
  
# Trusted Domains (higher confidence)
trusted_domains:
  - .gov
  - .edu
  - nih.gov
  - cms.gov
  - healthgrades.com
  - doximity.com
  - vitals.com