# Healthcare COI Analytics Configuration

# Health System
health_system:
  name: Northwell Health
  short_name: northwell
  npi_file: data/inputs/northwell-npis.csv

# BigQuery settings
bigquery:
  project_id: data-analytics-389803
  temp_dataset: temp
  dataset: conflixis_agent
  production_dataset: conflixis_agent
  tables:
    open_payments: op_general_all_aggregate_static
    prescriptions: PHYSICIAN_RX_2020_2024

# Analysis settings
analysis:
  start_year: 2020
  end_year: 2024
  
# Provider settings
provider:
  npi_file: data/inputs/northwell-npis.csv
  
# Risk scoring thresholds
risk_scoring:
  thresholds:
    high: 0.7
    medium: 0.4
  weights:
    payment_amount: 0.3
    payment_frequency: 0.2
    prescription_volume: 0.25
    specialty_risk: 0.15
    consecutive_years: 0.1

# Report settings
report:
  output_dir: reports
  template_dir: templates